apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: spark-integration-test
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: localhost:5000/minio/minio:RELEASE.2021-06-17T00-10-46Z
          args: ['server', '/data']
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-basic-auth-secret
                  key: username
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-basic-auth-secret
                  key: password
