apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: spark-integration-test
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: http
      protocol: TCP
      port: 9000
      nodePort: 30090
